DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sam') THEN
        CREATE SCHEMA sam;
    END IF;
END $EF$;


CREATE TABLE sam."Contact" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(128) NOT NULL,
    createdutc timestamp with time zone NOT NULL,
    property text,
    CONSTRAINT pk_contact PRIMARY KEY (id)
);


CREATE TABLE sam."Address" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    line1 character varying(512),
    line2 character varying(512),
    city character varying(512),
    state character varying(512),
    postalcode character varying(512),
    contactid integer NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT fk_address_contact_contactid FOREIGN KEY (contactid) REFERENCES sam."Contact" (id) ON DELETE CASCADE
);


CREATE INDEX ix_address_contactid ON sam."Address" (contactid);



