DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sam') THEN
        CREATE SCHEMA sam;
    END IF;
END $EF$;


CREATE TABLE sam."Contact" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(128) NOT NULL,
    "CreatedUtc" timestamp with time zone NOT NULL,
    "Property" text,
    CONSTRAINT "PK_Contact" PRIMARY KEY ("Id")
);


CREATE TABLE sam."Address" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Line1" character varying(512),
    "Line2" character varying(512),
    "City" character varying(512),
    "State" character varying(512),
    "PostalCode" character varying(512),
    "ContactId" integer NOT NULL,
    CONSTRAINT "PK_Address" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Address_Contact_ContactId" FOREIGN KEY ("ContactId") REFERENCES sam."Contact" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Address_ContactId" ON sam."Address" ("ContactId");



