DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sam') THEN
        CREATE SCHEMA sam;
    END IF;
END $EF$;


CREATE TABLE sam.contact (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(128) NOT NULL,
    property text,
    createdby character varying(128) NOT NULL,
    modifiedby character varying(128) NOT NULL,
    createdutc timestamp with time zone NOT NULL,
    modifiedutc timestamp with time zone NOT NULL,
    CONSTRAINT pk_contact PRIMARY KEY (id)
);


CREATE TABLE sam.address (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    line1 character varying(512),
    line2 character varying(512),
    city character varying(512),
    state character varying(512),
    postalcode character varying(512),
    contactid integer NOT NULL,
    createdby character varying(128) NOT NULL,
    modifiedby character varying(128) NOT NULL,
    createdutc timestamp with time zone NOT NULL,
    modifiedutc timestamp with time zone NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT fk_address_contact_contactid FOREIGN KEY (contactid) REFERENCES sam.contact (id) ON DELETE CASCADE
);


CREATE INDEX ix_address_contactid ON sam.address (contactid);



