// <auto-generated />
using System;
using Crm.Admin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crm.Admin.Migrations.Postgres
{
    [DbContext(typeof(CrmPostgresMigration))]
    [Migration("20260419235447_CrmPostgresMigration_v2")]
    partial class CrmPostgresMigration_v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crm.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("city");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contactid");

                    b.Property<string>("Line1")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("line2");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("postalcode");

                    b.Property<string>("State")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_address_contactid");

                    b.ToTable("address", "crm");
                });

            modelBuilder.Entity("Crm.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actorid");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer")
                        .HasColumnName("changetype");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entityid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entitytype");

                    b.Property<string>("Json")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("json");

                    b.Property<DateTime>("UtcTimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utctimestamp");

                    b.HasKey("Id")
                        .HasName("pk_audit");

                    b.ToTable("audit", "crm");
                });

            modelBuilder.Entity("Crm.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_company_name");

                    b.ToTable("company", "crm");
                });

            modelBuilder.Entity("Crm.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_contact_companyid");

                    b.ToTable("contact", "crm");
                });

            modelBuilder.Entity("Crm.Models.Address", b =>
                {
                    b.HasOne("Crm.Models.Contact", "Contact")
                        .WithMany("Addresses")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_contact_contactid");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Crm.Models.Contact", b =>
                {
                    b.HasOne("Crm.Models.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_company_companyid");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Crm.Models.Company", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Crm.Models.Contact", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
