// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sample.Admin;

#nullable disable

namespace Sample.Admin.Migrations.Postgres
{
    [DbContext(typeof(SamplePostgresMigration))]
    [Migration("20251031211223_SamplePostgresMigration_v3")]
    partial class SamplePostgresMigration_v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sam")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sample.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("city");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer")
                        .HasColumnName("contactid");

                    b.Property<string>("Line1")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("line2");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("postalcode");

                    b.Property<string>("State")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_address_contactid");

                    b.ToTable("address", "sam");
                });

            modelBuilder.Entity("Sample.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdutc");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedutc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Property")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("property");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.ToTable("contact", "sam");
                });

            modelBuilder.Entity("Sample.Models.Address", b =>
                {
                    b.HasOne("Sample.Models.Contact", "Contact")
                        .WithMany("Addresses")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_contact_contactid");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Sample.Models.Contact", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
