using Albatross.CommandLine;
using Albatross.CommandLine.Defaults;
using Albatross.EFCore;
using Albatross.Config;
using Albatross.EFCore.Admin;
using Albatross.EFCore.PostgreSQL;
using Albatross.EFCore.SqlServer;
using Crm.Models;
using Crm.Services;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.CommandLine;
using System.Threading.Tasks;
using Crm.Admin.AutoGenerated;

namespace Crm.Admin {
	internal class Program {
		static async Task<int> Main(string[] args) {
			if (Microsoft.EntityFrameworkCore.EF.IsDesignTime) {
				await new HostBuilder().Build().RunAsync();
				return 0;
			} else {
				await using var host = new CommandHost("Crm Admin Program")
					.RegisterServices(RegisterServices)
					.AddCommands()
					.Parse(args)
					.WithDefaults(AppContext.BaseDirectory)
					.Build();
				return await host.InvokeAsync();
			}
		}
		static void RegisterServices(ParseResult result, IServiceCollection services) {
			services.AddCrmDbSession().AddCrm();
			services.AddSingleton<IGetCurrentActorId<Guid>, SystemActorId>();
			services.AddScoped<ICommandErrorHandler, CrmCommandErrorHandler>();
			var key = result.CommandResult.Command.GetCommandKey();
			if (key.StartsWith("sqlserver")) {
				services.AddConfig<ICrmConfig, Crm.Models.SqlServer.CrmConfig>();
				services.AddSingleton<IExecuteScriptFile, ExecuteSqlServerScriptFile>();
				// this is only used by migration.  it has a diff DbContextOptions than the normal CrmDbSession
				services.AddScoped(provider => new CrmSqlServerMigration(provider.GetRequiredService<ICrmConfig>().ConnectionString));
				services.AddSqlServer<CrmDbSession>(provider => provider.GetRequiredService<ICrmConfig>().ConnectionString, true, (builder, sp) => builder.AddCrmInterceptors(sp));
			} else if (key.StartsWith("postgres")) {
				services.AddConfig<ICrmConfig, Crm.Models.Postgres.CrmConfig>();
				services.AddSingleton<IExecuteScriptFile, ExecuteScriptFile>();
				// this is only used by migration.  it has a diff DbContextOptions than the normal CrmDbSession
				services.AddScoped(provider => new CrmPostgresMigration(provider.GetRequiredService<ICrmConfig>().ConnectionString));
				services.AddPostgres<CrmDbSession>(provider => provider.GetRequiredService<ICrmConfig>().ConnectionString, true, (builder, sp) => builder.AddCrmInterceptors(sp));
			}
			services.RegisterCommands();
		}
	}
}