using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Data;
using System.Reflection;

namespace Albatross.EFCore {
	/// <summary>
	/// Base <see cref="DbContext"/> that implements <see cref="IDbSession"/>.
	/// </summary>
	/// <remarks>
	/// Override <see cref="OnModelCreating"/> and call the code-generated <c>BuildEntityModels</c> extension
	/// to register all <see cref="IBuildEntityModel"/> implementations in the assembly:
	/// <code>
	/// protected override void OnModelCreating(ModelBuilder modelBuilder) {
	///     modelBuilder.BuildEntityModels();
	///     modelBuilder.HasDefaultSchema(My.Schema.Sample);
	/// }
	/// </code>
	/// <c>BuildEntityModels</c> is generated by the <c>Albatross.EFCore.CodeGen</c> source generator.
	/// Reference it with <c>PrivateAssets="all"</c> to prevent the generator from running again
	/// in downstream projects, which would cause conflicts with their own generated code.
	/// If the source generator is not available, call each <see cref="EntityMap{T}"/> manually in <c>OnModelCreating</c>.
	/// <para/>
	/// All <c>string</c> columns default to <c>varchar</c> (non-Unicode). This works correctly with
	/// UTF-8 database collations and avoids unnecessary storage overhead. Override
	/// <see cref="ConfigureConventions"/> to revert globally, or apply <c>[Unicode(true)]</c> per-column
	/// when <c>nvarchar</c> is explicitly required.
	/// </remarks>
	public abstract class DbSession : DbContext, IDbSession {
		#region constants
		public const string Any = "any";
		public const string EFMigrationHistory = "__EFMigrationsHistory";
		protected readonly ILogger? logger;
		#endregion

		public DbContext DbContext => this;
		public IDbConnection DbConnection => Database.GetDbConnection();
		public virtual string NamespacePrefix => string.Empty;

		public DbSession(DbContextOptions option) : base(option) { }
		protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) {
			base.ConfigureConventions(configurationBuilder);
			configurationBuilder.Properties<string>().AreUnicode(false);
		}
	}
}