services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    shm_size: 256mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: alba
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data:
    external: true
